import { environment } from '../environments/environment';
// DO NOT EDIT THIS FILE, EDIT THE WEBPACK COMMON CONFIG INSTEAD, WHICH WILL MODIFY THIS FILE
let _VERSION = '1.0.0'; // This value will be overwritten by webpack
let _DEBUG_INFO_ENABLED = true; // This value will be overwritten by webpack
/* @toreplace VERSION */
/* @toreplace DEBUG_INFO_ENABLED */
export const VERSION = _VERSION;
export const DEBUG_INFO_ENABLED = _DEBUG_INFO_ENABLED;

export const API_URL = environment.API_URL;  //视频AI本地环境
export const FILE_URL = environment.API_URL; //视频AI系统专网分布式文件URL

